nginx_upgrade_dir: /root/nginx-upgrade
nginx_backup_dir: /etc
nginx_backup_prefix: nginx_main_backup
nginx_config_dir: /etc/nginx
nginx_service_name: nginx
artifactory_url: "https://artifactory.axisb.com/artifactory/thanos-generic-local/nginx/{{ nginx_file_name }}.zip"
nginx_extracted_dir: "{{ nginx_upgrade_dir }}/{{ nginx_file_name }}"
nginx_rpm_glob: "{{ nginx_extracted_dir }}/*.rpm"
nginx_plus_base_package: "nginx-plus"
nginx_plus_module_prefix: "nginx-plus-module-"
nginx_plus_module_names:
  - "xslt"
  - "geoip"
  - "perl"
  - "image-filter"