---
- name: Upgrade NGINX on target host(s)
  hosts: "{{ host }}"
  become: true
  vars_files:
     - ../inventories/development/group_vars/nginx.yml
  roles:
    - nginx_install
    - nginx_plus_install